### 넘파이 배열  
파이썬 리스트의 단점인 원소의 자료형 지정 불가, 많은 메모리 차지의 문제를 해결하고자 수치 해석 프로그램에서는 numpy라고하는 배열 패키지를 사용함  
numpy 배열의 경우 자체적 C언어로 구현되어 있어 자료형 지정과 메모리 절약 효과를 볼 수 있음  

### NumPy import  
numpy 패키지를 사용하려면 먼저 패키지를 설치해야 함  
```bash
    pip install numpy
```
numpy 패키지를 프로그램에서 사용하려면 import 해야 함
``` python
    import numpy
    import numpy as np
```

In [165]:
import numpy as np

In [8]:
ndarray_ = np.array([0, 1, 2, 3, 4])
ndarray_

array([0, 1, 2, 3, 4])

파이썬 리스트와는 다르게 numpy의 배열의 요소는 모두 같은 타입이어야 함  
이러한 numpy 배열의 특성 때문에 요소에 대한 접근 속도가 빠름  

In [9]:
ndarray_ = np.array([1, 1.5, 2])
ndarray_

array([1. , 1.5, 2. ])

In [10]:
ndarray_ = np.array(['문자열', 1, 1.5])
ndarray_

array(['문자열', '1', '1.5'], dtype='<U32')

### 벡터화 연산
numpy 배열은 각 원소에 대한 반복 연산을 간단한 명령으로 처리할 수 있는 벡터화 연산을 지원

In [11]:
# 각 요소를 2씩 곱하는 연산
# 리스트를 사용했을 경우
numbers = list(range(10))
result = []
for number in numbers:
    result.append(number*2)
    
result

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [12]:
# numpy array를 사용했을 때
numpy_numbers = np.array(range(10))
result = 2 * numpy_numbers
result

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
result = 2 * numbers
result

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

numpy 배열의 벡터화 연산은 모든 종류의 연산에 적용이 가능하다

In [14]:
numbers1 = np.array(list(range(5)))
numbers2 = np.array(list(range(5, 10)))
numbers1, numbers2

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [15]:
result = numbers1 * 5 + numbers2
result

array([ 5, 11, 17, 23, 29])

In [16]:
result = numbers1 == 3 
result

array([False, False, False,  True, False])

In [17]:
result = (numbers1 > 2) & (numbers2 < 10)
result

numbers1 > 2, numbers2 < 10, result

(array([False, False, False,  True,  True]),
 array([ True,  True,  True,  True,  True]),
 array([False, False, False,  True,  True]))

### 2차원 배열
2차원 배열을 생성할 때는 요소를 리스트로 가지는 리스트를 `array()`의 매개변수로 전달하면 2차원 배열을 생성할 수 있음 

In [18]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
numpy_matrix = np.array(matrix)
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
len(numpy_matrix)

3

In [20]:
numpy_matrix[0]

array([1, 2, 3])

In [21]:
len(numpy_matrix[0])

3

### 3차원 배열 만들기  
리스트의 요소로 2차원형태를 띄는 리스트를 지정하면 3차원 배열로 만들 수 있다

In [22]:
three_d = [
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
]

numpy_3d = np.array(three_d)
numpy_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### 배열의 차원과 크기 구하기
`ndim`: 배열의 차원을 정수로 반환  
`shape`: 배열의 각 차원의 크기를 정수의 튜플로 반환

In [23]:
numpy_matrix.ndim, numpy_matrix.shape

(2, (3, 3))

In [24]:
numpy_3d.ndim, numpy_3d.shape

(3, (2, 3, 4))

### numpy 배열의 인덱싱
일반적으로 배열변수[인덱스] 의 형태로 사용  
다차원 형태일 경우는 일반 리스트와는 다르게 `배열변수[인덱스, 인덱스, ...]`의 형태로 사용함  
- 일반 2차원 리스트: `리스트[인덱스][인덱스]`  
- numpy 2차원 배열 : `배열[인덱스][인덱스]  

In [25]:
# 일반 3차원 리스트
three_d

[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
 [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]

In [26]:
three_d[1][0][3]

16

In [27]:
# numpy 3차원 배열
numpy_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### numby 배열 슬라이싱  
일반 리스트에서 사용하는 배열 슬라이싱 방법, `리스트[시작인덱스:종료인덱스]`와 동일함  
단,다차원 배열인 경우 인덱스를 여러개 저장할때 `,`를 써야하는 것에 주의

In [28]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
numpy_matrix[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
numpy_matrix[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
numpy_matrix[0, :2]

array([1, 2])

In [32]:
numpy_matrix[:2, 0]

array([1, 4])

In [33]:
numpy_matrix[1:, 1:]

array([[5, 6],
       [8, 9]])

In [34]:
numpy_3d[:1, :2, :2]

array([[[1, 2],
        [5, 6]]])

##### 파이썬으로 다음 연산을 수행한다.     

다음 행렬과 같은 행렬이 있다.

```python
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
```

1. 이 행렬에서 값 7 을 인덱싱한다.
2. 이 행렬에서 값 14 을 인덱싱한다.
3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다

In [35]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [36]:
m[1][2]

7

In [37]:
m[-1, -1]

14

In [38]:
m[2][4]

14

In [39]:
m[1:, 1:3]

array([[ 6,  7],
       [11, 12]])

In [40]:
m[1:, 2]

array([ 7, 12])

In [41]:
m[0:2, 3:5]

array([[3, 4],
       [8, 9]])

### 배열 인덱싱
**팬시 인덱싱**이라고 부르는 배열 인덱싱 기법이 존재
이 벼열 인덱싱은 인덱스로부터 정수형태나 슬라이스 형태로 인덱스를 전달하는것이 아니라  
인덱스로 또 다른 넘파일 배열을 전달하여 그에 부합하는 새로운 배열을 반환

#### 불리언 배열 인덱싱  
`True`, `False`두 형태로만 이루어진 배열을 인덱스로 전달하여 `True`가 위치한 값만 반환하여 새로운 배열을 만드는 인덱싱 기법  
불리언 배열 인덱싱 기법은 기본 배열과 인덱스로 전달하는 배열의 크기가 같아야함

In [42]:
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
index_array = np.array([True, True, False, False, False, True, True, True])
numpy_array[index_array]

array([1, 2, 6, 7, 8])

조건 연산을 통해서도 불리언 인덱싱 처리를 할 수 있음

In [43]:
numpy_array % 2

array([1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [44]:
numpy_array % 2 == 0

array([False,  True, False,  True, False,  True, False,  True])

In [45]:
numpy_array[numpy_array % 2 == 0]

array([2, 4, 6, 8])

#### 정수 배열 인덱싱
인덱스 배열의 원소의 값이 기존 넘파이 배열의 원소 인덱스를 가리키는 정수로 구성된 배열을 인덱스로 전달하여  
해당하는 인덱스의 값들로 새로운 배열을 반환하는 기법

In [46]:
numpy_array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
index_array = np.array([0 ,2 ,3])

In [48]:
numpy_array[index_array]

array([1, 3, 4])

인덱스 배열로 사용되는 정수 배열은 기존 배열의 길이보다 커도 사용가능  
이때, 반환되는 배열의 길이는 인덱스 배열로 전달한 배열의 길이로 결정이 됨  

인덱스 배열로 사용되는 정수 배열의 요소는 기존 배열의 최대 인덱스 범위를 벗어나는 값이 존재할 경우 예외발생

In [49]:
index_array = np.array([0,2,3,6,0,2,3,6,0,2,3,6])

In [50]:
numpy_array[index_array]

array([1, 3, 4, 7, 1, 3, 4, 7, 1, 3, 4, 7])

#### 다차원 배열에서 배열 인덱싱

In [51]:
index_array = np.array([True, False, True])
numpy_matrix[:2, index_array]   

array([[1, 3],
       [4, 6]])

In [52]:
# 배열 인덱스 값으로 정수 리스트를 전달하면 배열의 순서가 변경 됨
numpy_matrix[[2, 1, 0],:]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

**파이썬으로 다음 연산을 수행한다.**
다음 행렬과 같은 배열이 있다.

```
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
```

1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
</aside>

In [53]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [54]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [55]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [56]:
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

In [57]:
numpy_array = np.array([1, 2, 3])
numpy_array.dtype

dtype('int32')

In [58]:
numpy_array = np.array([1.0, 2.0, 3.0])
numpy_array.dtype

dtype('float64')

In [59]:
numpy_array = np.array(['1', '2', '3'])
numpy_array.dtype

dtype('<U1')

`array()`함수를 사용하여 배열을 생성할 때 명시적으로 데이터 타입을 지정하지 않으면 자동으로 데이터 타입을 추론하여 지정하게 됨  
만약, 명시적으로 데이터 타입을 지정하고자 한다면 `array()`함수에 `dtype`매개변수로 데이터 타입을 지정해주면 됨

##### dtype의 접두사
b:불리언, i:정수, f:실수, U:유니코드

In [60]:
numpy_array = np.array(['1.0', '2.0', '3.0'], dtype='f')
numpy_array.dtype

dtype('float32')

In [61]:
numpy_array

array([1., 2., 3.], dtype=float32)

### numpy에서 Inf 와 NaN
numpy 배열 연산에서 1을 0으로 나누면 `inf`, -1을 0으로 나누면 `NaN`이 반환됨

### 배열 생성
numpy 배열을 생성하는 방법
- `zeros`, `ones`
- `zeros_like`, `ones_like`
- `empty`
- `arange`
- `linspace`,  `logspace`

#### zeros
크기가 정해져 있고 원소를 0으로 초기화한 배열을 생성하는 함수

In [62]:
numpy_array = np.zeros(5)
numpy_array

array([0., 0., 0., 0., 0.])

In [63]:
# 매개변수로 튜플을 전달하여 다차원 배열생성도 가능
numpy_array = np.zeros((2, 3))
numpy_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [64]:
# dtype을 명시하여 데이터 타입을 지정할 수 있음
numpy_array = np.zeros((2, 3), dtype='i')
numpy_array

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

만약, dtype으로 문자열(U)를 지정하게 되면 문자열의 길이가 초과하면 초과된 부분이 손실됨

#### ones
크기가 정해져있고, 원소를 1로 초기화한 배열을 생성하는 함
`zeros`함수와 사용법 동일

In [65]:
ones_array = np.ones((3, 2, 2), dtype='i')
ones_array

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

#### zeros_like, ones_like
크기를 직접 지정하지 않고 이미 존재하는 배열의 크기를 본따서 0또는 1로 채워진 배열을 생성하는 함수

In [66]:
zeros_array = np.zeros_like(ones_array,dtype='f')
zeros_array

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]], dtype=float32)

#### empty
크기만 지정하고 원소의 값은 '쓰레기 데이터'로 채워진 배열을 생성
`zeros` 또는 `ones` 함수를 사용하여 배열을 생성하는 것 보다 배열 생성속도가 빠르다

In [67]:
empty_array = np.empty((10, 10))
empty_array

array([[0.00000000e+000, 0.00000000e+000, 4.94065646e-324,
        6.95210103e-310, 4.69362364e-322, 1.08645720e-311,
        1.08645720e-311, 1.08645720e-311, 1.08645731e-311,
        1.08645720e-311],
       [1.08645720e-311, 1.08645720e-311, 1.08645720e-311,
        1.08645720e-311, 1.08645731e-311, 1.08645720e-311,
        1.08645720e-311, 1.08645720e-311, 1.08645720e-311,
        1.08645720e-311],
       [1.08645720e-311, 1.08645731e-311, 1.08645720e-311,
        1.08645720e-311, 1.08645720e-311, 1.08645720e-311,
        1.08645720e-311, 1.08645720e-311, 1.08645720e-311,
        1.08645731e-311],
       [1.08645720e-311, 1.08645720e-311, 1.08645720e-311,
        1.08645731e-311, 1.08645720e-311, 1.08645720e-311,
        1.08645720e-311, 1.08645720e-311, 1.08645720e-311,
        1.08645720e-311],
       [1.08645720e-311, 1.08645720e-311, 1.08645720e-311,
        1.08645720e-311, 1.08645720e-311, 1.08645720e-311,
        1.08645720e-311, 1.08645721e-311, 1.08645721e-311,
        1.0

#### arange
파이썬의 내장함수, `range()`함수와 동일한 기능을 하는 numpy배열 생성함수

In [68]:
arage_array = np.arange(10,50)
arage_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 전치연산
배열의 행과 열의 위치를 전치시키는 방법 배열의 `T`속성으로 반환 받을 수 있음

In [69]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
numpy_matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [71]:
numpy_3d.T

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

### 배열의 크기 변경
numpy 배열에서 원소의 개수를 유지한 상태로 배열의 형태를 변경하려 한다면 `reshape`메서드를 사용하여  
변경할 수 있음

In [72]:
numpy_array = np.zeros(12)
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [73]:
reshape_array = numpy_array.reshape(4, 3)
reshape_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
reshape_array = numpy_array.reshape(2, 6)
reshape_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

numpy 배열의 원소는 개수가 정해져 있기 때문에 `reshape`메서드에 하나의 인자로 -1을 넣게 되면 다른 인자들을 통해서 추론하여 지정

In [75]:
reshape_array = numpy_array.reshape(3, -1)
reshape_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
# reshape_array = numpy_array.reshape(5 ,-1)

만약 `reshape`메서드 인자들을 곱한 결과가 기존 배열의 원소의 총 합과 다르면 에러가 발생  
-1로 지정한 인자가 있을 때 해당 인자의 곱으로 총합을 계산할 수 없는 경우 에러가 발생

다차원 배열을 무조건 1차원 배열로 변경하려 한다면 `flatten`이나 `ravel`메서드를 사용

In [77]:
numpy_matrix = np.empty((3, 4))
numpy_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [78]:
numpy_array = numpy_matrix.flatten()
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [79]:
numpy_array = numpy_matrix.ravel()
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

배열 사용에서 주의할 점은 *길이가 6인 1차원배열* 과 *5x1인 2차원 배열* , *1x5인 2차원 배열* 은 서로 각각 다른 배열  
(요소의 개수와 내용, 순서가 모두 같더라도 형태가 다르면 다를 배열) 

차원을 한 차원 증가시키고자 한다면 `numpy.newaxis`속성으로 차원을 증가 시킬 수 있음

In [80]:
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [81]:
newaxis_array = numpy_array[:, np.newaxis]
newaxis_array

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

### 배열 연결하기
행의 수나 열의 수가 같은 두 개 이상의 배열을 연결하는 방법  
- `hstack` : 행의 수가 같은 두 개 이상의 배열을 연결  
- `vstack` : 열의 수가 같은 두 개 이상의 배열을 연결
- `dstack` : 행과 열의 수가 같은 두 개 이상의 배열을 연결
- `stack` : dstack의 확장기능으로 행과 열의 수가 같은 두 개 이상의 배열을 연결, 단 연결축을 개발자가 직접 지정
- `r_` : 배열의 요소를 연결, 메서드 인자를 `[]`에 전달한다
- `c_` : 행끼리 연결, 최소 2차원의 배열로 연결
- `tile` : 하나의 배열을 여러번 반복하여 연결

In [82]:
zeros_array = np.zeros((3, 4))
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [83]:
ones_array = np.ones((3, 2))
ones_array


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [84]:
hstack_array = np.hstack([zeros_array, ones_array])
hstack_array


array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

In [85]:
zeros_array = np.zeros((3, 4))
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [86]:
ones_array = np.ones((2, 4))
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [87]:
vstack_array = np.vstack([zeros_array, ones_array])
vstack_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [88]:
zeros_array = np.zeros((3, 3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [89]:
ones_array = np.ones((3, 3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [90]:
dstack_array = np.dstack([zeros_array, ones_array])
dstack_array

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

In [91]:
zeros_array, ones_array

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [92]:
stack_array = np.stack([zeros_array, ones_array], axis = 1)
stack_array

array([[[0., 0., 0.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [1., 1., 1.]]])

In [93]:
r_array = np.r_[zeros_array, ones_array]
r_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [94]:
c_array = np.c_[zeros_array, ones_array]
c_array

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [95]:
tile_array = np.tile(zeros_array, 2)
tile_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [96]:
tile_array = np.tile(zeros_array, (3, 2))
tile_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

##### 파이썬으로 다음 연산을 수행한다
지금까지 공부한 명령어를 사용하여 다음과 같은 배열을 만들어라.  
```python
    array([[   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.]])
```

In [97]:
a = np.zeros((3, 3))
b = np.ones((3, 2))
c = np.arange(10, 151, 10)
d = c.reshape(3, 5)

a, b, c, d

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150]),
 array([[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100],
        [110, 120, 130, 140, 150]]))

In [98]:
ab = np.hstack([a, b])
ab

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [99]:
abcd = np.vstack([ab, d])
abcd

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [100]:
fianl_abcd = np.tile(abcd, (2,1))
fianl_abcd

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

### 2차원 그리드 포인트 생성
좌표값의 쌍(그리드 포인트)을 생성하는 메서드 `meshgrid` 함수로 x축과 y축의 점들로 사각형의 영역을 나타내는 조합을 생성

In [101]:
x = np.arange(3)
x

array([0, 1, 2])

In [102]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [103]:
X, Y = np.meshgrid(x, y)
X, Y

(array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]))

In [104]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

### 벡터화 연산
numpy 배열은 반복문을 쓰지않고 배열에 대하여 벡터 연산 가능

In [105]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [106]:
%%time
z = np.zeros_like(x)
for i in range(len(x)):
    z[i] = x[i] + y[i]

CPU times: total: 0 ns
Wall time: 2.99 ms


In [107]:
%%time
z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [108]:
x = np.arange(5)
y = np.arange(10,15)
z = np.arange(5)

In [109]:
np.all(x == y)

False

In [110]:
np.all(x == z)

True

In [111]:
np.all(x <= y)

True

In [112]:
x

array([0, 1, 2, 3, 4])

In [113]:
x * 10

array([ 0, 10, 20, 30, 40])

In [114]:
10 ** x

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [115]:
x ** 10

array([      0,       1,    1024,   59049, 1048576], dtype=int32)

### 브로드캐스팅
차원이 서로 다른 배열을 연산하는 기능, 부족한 차원에 대하여 반복확장하여 배열의 크기가 큰 배열에 크기를 맞춘 후 연산을 진행한다

In [116]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [117]:
x + 1

array([1, 2, 3, 4, 5])

In [118]:
x = np.arange(15)
x = x.reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [119]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [120]:
x + y

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18]])

In [121]:
y = np.arange(3)
y = y.reshape(3, 1)
y

array([[0],
       [1],
       [2]])

In [122]:
x + y

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16]])

### 차원 축소 연산
배열에 하나의 행을 하나의 집합으로 보고 구 집합에 대한 집계 처리 결과로 새로운 값을 반환하여 배열을 생성

In [123]:
x = np.arange(10)
x = x.reshape(2, 5)

In [124]:
x.max()

9

In [125]:
x.min()

0

In [126]:
x.mean()

4.5

In [127]:
x.sum(axis = 0 )

array([ 5,  7,  9, 11, 13])

In [128]:
x.sum(axis = 1)

array([10, 35])

### 정렬
`sort`메서드로 배열을 정렬 할 수 있다.  
`axis`매개변수로 정렬 기준을 정할 수 있음  
`axis = 0`: 행을 따로 분리하여 정렬  
`axis = 1`: 열을 따로 분리하여 정렬  
따로 지정하지 않을 시 가장 나중 차원을 기준으로 정렬

In [129]:
x = np.array(
    [[5, 2, 7, 4],
    [11, 8, 6, 5],
    [8, 5, 11, 2]])
x

array([[ 5,  2,  7,  4],
       [11,  8,  6,  5],
       [ 8,  5, 11,  2]])

In [130]:
x. sort()
x

array([[ 2,  4,  5,  7],
       [ 5,  6,  8, 11],
       [ 2,  5,  8, 11]])

In [131]:
x.sort(axis = 0)
x

array([[ 2,  4,  5,  7],
       [ 2,  5,  8, 11],
       [ 5,  6,  8, 11]])

In [132]:
x.sort(axis = 1)
x

array([[ 2,  4,  5,  7],
       [ 2,  5,  8, 11],
       [ 5,  6,  8, 11]])

In [133]:
np.argsort(x)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

*** 넘파이로 다음 연산을 수행한다

실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.

1. 전체의 최댓값
2. 각 행의 합
3. 각 행의 최댓값
4. 각 열의 평균
5. 각 열의 최솟값


In [134]:
x = np.array([
    [5, 11, 12],
    [0, 18, 22],
    [8, 2, 7]]
)

In [135]:
x.max()

22

In [136]:
x.sum()

85

In [137]:
x.max(axis = 1)

array([12, 22,  8])

In [138]:
x.mean(axis = 0)

array([ 4.33333333, 10.33333333, 13.66666667])

In [139]:
x.min(axis = 0)

array([0, 2, 7])

### Sumpy 배열 통계 연산
- 데이터 개수 구하기: `len()`내장 함수
- 표본 평균 " : `mean()`내장 함수
- 표본 분산 : `var()`내장 함수
- 표본 표준편차 : `std(`) 내장 함수
- 최대/최소 : `max()`=`min()` 내장 함수
- 중앙값 : `median`내장 함수
- 사분위수 : `percentile`내장 함수

In [140]:
samples = np.array([9, 1, 4, 20, 24, 2, 23, 92, 24, -23])
samples

array([  9,   1,   4,  20,  24,   2,  23,  92,  24, -23])

In [141]:
sample_volume = len(samples)
sample_volume

10

In [142]:
sample_mean = samples.mean()
sample_mean

17.6

In [143]:
sample_mean = np.mean(samples)
sample_mean

17.6

In [144]:
sample_variance = samples.var()
sample_variance

807.8399999999999

In [145]:
sample_variance = np.var(samples)
sample_variance

807.8399999999999

In [146]:
sample_standaed = samples.std()
sample_standaed

28.422526277584826

In [147]:
samples_max = samples.max()
samples_max

92

In [148]:
sample_median = np.median(samples)
sample_median

14.5

### 난수 생성에 필요한 시드 설정
numpy 패키지에 있는  `seed()`메서드에 매개변수로 난수 생성 시 필요한 시드를 설정

In [149]:
np.random.seed(10)

In [150]:
random_array = np.random.rand(10)
random_array

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

### 데이터 순서를 임의로 바꾸기
numpy 패키지의 random 하위 패키지의 `suffle` 메서드로 배열을 임의 순서로 변경 가능(자체 변환)


In [151]:
range_array = np.arange(10)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
np.random.shuffle(range_array)
range_array

array([1, 6, 2, 5, 7, 8, 9, 0, 3, 4])

### 데이터 샘플링
모집단 배열에 표본으로 사용할 표본 집단 배열을 무작위로 선택하는 방법  
numpy 패키지의 random하위패키지의 `choice(모집단배열, 표본크기, 중복선택여부, 중복선택여부,각요소의 선택확률배열)` 메서드로 사용 가능

In [153]:
population_array = np.arange(10)
population_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
sample_array = np.random.choice(population_array, 5)
sample_array

array([1, 8, 4, 1, 3])

In [155]:
sample_array = np.random.choice(population_array, 5, replace = False)
sample_array

array([7, 0, 9, 2, 4])

In [156]:
probabaility_array = [0.1, 0.05, 0.05, 0, 0.15, 0.25, 0.1, 0.05, 0.05, 0.2]
sample_array = np.random.choice(population_array, 10000, p = probabaility_array)
sample_array

array([9, 1, 4, ..., 6, 5, 4])

### 난수 배열 생성
- `rand()` : 0과 1사이의 균일 분포를 따르는 난수 배열 생성
- `randn()` : 표준 정규 분포를 따르는 난수 배열 생성
 - `randInt(low, high = 정수, size = 정수 혹은 튜플) : 지정한 범위 정수의 균일 분포를 따르는 난수배열 생성

In [157]:
rand_array = np.random.rand(10)
rand_array

array([0.44412203, 0.35791187, 0.7206251 , 0.18170859, 0.31626429,
       0.83468386, 0.87733557, 0.21044951, 0.5523731 , 0.69508672])

In [158]:
randn_array = np.random.randn(10)
randn_array

array([-1.38847565, -0.56596746,  1.05326217, -0.54679125, -0.70799069,
       -0.14678624, -1.26912637,  1.16255401,  0.54930504,  1.47993753])

In [159]:
randint_array = np.random.randint(10)
randint_array

7

In [160]:
randint_array = np.random.randint(10, high = 20, size = 10)
randint_array

array([16, 10, 15, 19, 16, 16, 18, 18, 10, 17])

### 정수 데이터 카운팅
배열의 요소가 정순이면 `unique()`메서드나 `bincount()`메서드로 간단하게 분석 할 수 있다

In [161]:
analysis_array = np.unique(sample_array, return_counts=True)
analysis_array

(array([0, 1, 2, 4, 5, 6, 7, 8, 9]),
 array([ 976,  501,  455, 1526, 2531,  964,  545,  492, 2010], dtype=int64))

In [163]:
analysis_array = np.bincount(sample_array, minlength=10)
analysis_array

array([ 976,  501,  455,    0, 1526, 2531,  964,  545,  492, 2010],
      dtype=int64)

파이썬으로 다음 연산을 수행한다.

가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자.  nbbb
250일 동안의 주가를 무작위로 생성하라

파이썬으로 다음 연산을 수행한다.

가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자.  nbbb
250일 동안의 주가를 무작위로 생성하라

 price = 10000
 variation_ranges = (np.random.randn(250)/100)+1
 variation_ranges

stock_prices = []
for ratio in variation_ranges:
