### 넘파이 배열  
파이썬 리스트의 단점인 원소의 자료형 지정 불가, 많은 메모리 차지의 문제를 해결하고자 수치 해석 프로그램에서는 numpy라고하는 배열 패키지를 사용함  
numpy 배열의 경우 자체적 C언어로 구현되어 있어 자료형 지정과 메모리 절약 효과를 볼 수 있음  

### NumPy import  
numpy 패키지를 사용하려면 먼저 패키지를 설치해야 함  
```bash
    pip install numpy
```
numpy 패키지를 프로그램에서 사용하려면 import 해야 함
``` python
    import numpy
    import numpy as np
```

In [2]:
import numpy as np

In [3]:
ndarray_ = np.array([0, 1, 2, 3, 4])
ndarray_

array([0, 1, 2, 3, 4])

파이썬 리스트와는 다르게 numpy의 배열의 요소는 모두 같은 타입이어야 함  
이러한 numpy 배열의 특성 때문에 요소에 대한 접근 속도가 빠름  

In [4]:
ndarray_ = np.array([1, 1.5, 2])
ndarray_

array([1. , 1.5, 2. ])

In [5]:
ndarray_ = np.array(['문자열', 1, 1.5])
ndarray_

array(['문자열', '1', '1.5'], dtype='<U32')

### 벡터화 연산
numpy 배열은 각 원소에 대한 반복 연산을 간단한 명령으로 처리할 수 있는 벡터화 연산을 지원

In [6]:
# 각 요소를 2씩 곱하는 연산
# 리스트를 사용했을 경우
numbers = list(range(10))
result = []
for number in numbers:
    result.append(number*2)
    
result

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [7]:
# numpy array를 사용했을 때
numpy_numbers = np.array(range(10))
result = 2 * numpy_numbers
result

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
result = 2 * numbers
result

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

numpy 배열의 벡터화 연산은 모든 종류의 연산에 적용이 가능하다

In [9]:
numbers1 = np.array(list(range(5)))
numbers2 = np.array(list(range(5, 10)))
numbers1, numbers2

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [10]:
result = numbers1 * 5 + numbers2
result

array([ 5, 11, 17, 23, 29])

In [11]:
result = numbers1 == 3 
result

array([False, False, False,  True, False])

In [12]:
result = (numbers1 > 2) & (numbers2 < 10)
result

numbers1 > 2, numbers2 < 10, result

(array([False, False, False,  True,  True]),
 array([ True,  True,  True,  True,  True]),
 array([False, False, False,  True,  True]))

### 2차원 배열
2차원 배열을 생성할 때는 요소를 리스트로 가지는 리스트를 `array()`의 매개변수로 전달하면 2차원 배열을 생성할 수 있음 

In [13]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
numpy_matrix = np.array(matrix)
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
len(numpy_matrix)

3

In [15]:
numpy_matrix[0]

array([1, 2, 3])

In [16]:
len(numpy_matrix[0])

3

### 3차원 배열 만들기  
리스트의 요소로 2차원형태를 띄는 리스트를 지정하면 3차원 배열로 만들 수 있다

In [17]:
three_d = [
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
]

numpy_3d = np.array(three_d)
numpy_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### 배열의 차원과 크기 구하기
`ndim`: 배열의 차원을 정수로 반환  
`shape`: 배열의 각 차원의 크기를 정수의 튜플로 반환

In [18]:
numpy_matrix.ndimm, numpy_matrix.shape

AttributeError: 'numpy.ndarray' object has no attribute 'ndimm'

In [ ]:
numpy_3d.ndim, numpy_3d.shape

(3, (2, 3, 4))

### numpy 배열의 인덱싱
일반적으로 배열변수[인덱스] 의 형태로 사용  
다차원 형태일 경우는 일반 리스트와는 다르게 `배열변수[인덱스, 인덱스, ...]`의 형태로 사용함  
- 일반 2차원 리스트: `리스트[인덱스][인덱스]`  
- numpy 2차원 배열 : `배열[인덱스][인덱스]  

In [ ]:
# 일반 3차원 리스트
three_d

[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
 [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]

In [ ]:
three_d[1][0][3]

16

In [ ]:
# numpy 3차원 배열
numpy_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### numby 배열 슬라이싱  
일반 리스트에서 사용하는 배열 슬라이싱 방법, `리스트[시작인덱스:종료인덱스]`와 동일함  
단,다차원 배열인 경우 인덱스를 여러개 저장할때 `,`를 써야하는 것에 주의

In [ ]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
numpy_matrix[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
numpy_matrix[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
numpy_matrix[0, :2]

array([1, 2])

In [ ]:
numpy_matrix[:2, 0]

array([1, 4])

In [ ]:
numpy_matrix[1:, 1:]

array([[5, 6],
       [8, 9]])

In [ ]:
numpy_3d[:1, :2, :2]

array([[[1, 2],
        [5, 6]]])

##### 파이썬으로 다음 연산을 수행한다.     

다음 행렬과 같은 행렬이 있다.

```python
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
```

1. 이 행렬에서 값 7 을 인덱싱한다.
2. 이 행렬에서 값 14 을 인덱싱한다.
3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다

In [ ]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [ ]:
m[1][2]

7

In [ ]:
m[-1, -1]

14

In [ ]:
m[2][4]

14

In [ ]:
m[1:, 1:3]

array([[ 6,  7],
       [11, 12]])

In [ ]:
m[1:, 2]

array([ 7, 12])

In [ ]:
m[0:2, 3:5]

array([[3, 4],
       [8, 9]])

### 배열 인덱싱
**팬시 인덱싱**이라고 부르는 배열 인덱싱 기법이 존재
이 벼열 인덱싱은 인덱스로부터 정수형태나 슬라이스 형태로 인덱스를 전달하는것이 아니라  
인덱스로 또 다른 넘파일 배열을 전달하여 그에 부합하는 새로운 배열을 반환

#### 불리언 배열 인덱싱  
`True`, `False`두 형태로만 이루어진 배열을 인덱스로 전달하여 `True`가 위치한 값만 반환하여 새로운 배열을 만드는 인덱싱 기법  
불리언 배열 인덱싱 기법은 기본 배열과 인덱스로 전달하는 배열의 크기가 같아야함

In [ ]:
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
index_array = np.array([True, True, False, False, False, True, True, True])
numpy_array[index_array]

array([1, 2, 6, 7, 8])

조건 연산을 통해서도 불리언 인덱싱 처리를 할 수 있음

In [ ]:
numpy_array % 2

array([1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [ ]:
numpy_array % 2 == 0

array([False,  True, False,  True, False,  True, False,  True])

In [ ]:
numpy_array[numpy_array % 2 == 0]

array([2, 4, 6, 8])

#### 정수 배열 인덱싱
인덱스 배열의 원소의 값이 기존 넘파이 배열의 원소 인덱스를 가리키는 정수로 구성된 배열을 인덱스로 전달하여  
해당하는 인덱스의 값들로 새로운 배열을 반환하는 기법

In [ ]:
numpy_array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
index_array = np.array([0 ,2 ,3])

In [ ]:
numpy_array[index_array]

array([1, 3, 4, 7, 1, 3, 4, 7, 1, 3, 4, 7])

인덱스 배열로 사용되는 정수 배열은 기존 배열의 길이보다 커도 사용가능  
이때, 반환되는 배열의 길이는 인덱스 배열로 전달한 배열의 길이로 결정이 됨  

인덱스 배열로 사용되는 정수 배열의 요소는 기존 배열의 최대 인덱스 범위를 벗어나는 값이 존재할 경우 예외발생

In [ ]:
index_array = np.array([0,2,3,6,0,2,3,6,0,2,3,6])

In [ ]:
numpy_array(index_array)

TypeError: 'numpy.ndarray' object is not callable

#### 다차원 배열에서 배열 인덱싱

In [ ]:
index_array = np.array([True, False, True])
numpy_matrix[:2, index_array]   

array([[1, 3],
       [4, 6]])

In [ ]:
# 배열 인덱스 값으로 정수 리스트를 전달하면 배열의 순서가 변경 됨
numpy_matrix[[2, 1, 0],:]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

**파이썬으로 다음 연산을 수행한다.**
다음 행렬과 같은 배열이 있다.

```
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
```

1. 이 배열에서 3의 배수를 찾아라.
2. 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3. 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
</aside>

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [ ]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [ ]:
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

In [ ]:
numpy_array = np.array([1, 2, 3])
numpy_array.dtype

dtype('int32')

In [ ]:
numpy_array = np.array([1.0, 2.0, 3.0])
numpy_array.dtype

dtype('float64')

In [ ]:
numpy_array = np.array(['1', '2', '3'])
numpy_array.dtype

dtype('<U1')

`array()`함수를 사용하여 배열을 생성할 때 명시적으로 데이터 타입을 지정하지 않으면 자동으로 데이터 타입을 추론하여 지정하게 됨  
만약, 명시적으로 데이터 타입을 지정하고자 한다면 `array()`함수에 `dtype`매개변수로 데이터 타입을 지정해주면 됨

##### dtype의 접두사
b:불리언, i:정수, f:실수, U:유니코드

In [ ]:
numpy_array = np.array(['1.0', '2.0', '3.0'], dtype='f')
numpy_array.dtype

dtype('float32')

In [ ]:
numpy_array

array([1., 2., 3.], dtype=float32)

### numpy에서 Inf 와 NaN
numpy 배열 연산에서 1을 0으로 나누면 `inf`, -1을 0으로 나누면 `NaN`이 반환됨

### 배열 생성
numpy 배열을 생성하는 방법
- `zeros`, `ones`
- `zeros_like`, `ones_like`
- `empty`
- `arange`
- `linspace`,  `logspace`

#### zeros
크기가 정해져 있고 원소를 0으로 초기화한 배열을 생성하는 함수

In [ ]:
numpy_array = np.zeros(5)
numpy_array

array([0., 0., 0., 0., 0.])

In [ ]:
# 매개변수로 튜플을 전달하여 다차원 배열생성도 가능
numpy_array = np.zeros((2, 3))
numpy_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# dtype을 명시하여 데이터 타입을 지정할 수 있음
numpy_array = np.zeros((2, 3), dtype='i')
numpy_array

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

만약, dtype으로 문자열(U)를 지정하게 되면 문자열의 길이가 초과하면 초과된 부분이 손실됨

#### ones
크기가 정해져있고, 원소를 1로 초기화한 배열을 생성하는 함
`zeros`함수와 사용법 동일

In [ ]:
ones_array = np.ones((3, 2, 2), dtype='i')
ones_array

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

#### zeros_like, ones_like
크기를 직접 지정하지 않고 이미 존재하는 배열의 크기를 본따서 0또는 1로 채워진 배열을 생성하는 함수

In [ ]:
zeros_array = np.zeros_like(ones_array,dtype='f')
zeros_array

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]], dtype=float32)

#### empty
크기만 지정하고 원소의 값은 '쓰레기 데이터'로 채워진 배열을 생성
`zeros` 또는 `ones` 함수를 사용하여 배열을 생성하는 것 보다 배열 생성속도가 빠르다

In [ ]:
empty_array = np.empty((10, 10))
empty_array

array([[0.00000000e+000, 0.00000000e+000, 4.94065646e-324,
        6.95210043e-310, 4.69362364e-322, 1.25549769e-311,
        1.25549769e-311, 1.25549768e-311, 1.25549838e-311,
        1.25549769e-311],
       [1.25549768e-311, 1.25549769e-311, 1.25549768e-311,
        1.25549769e-311, 1.25549838e-311, 1.25549768e-311,
        1.25549769e-311, 1.25549769e-311, 1.25549769e-311,
        1.25549769e-311],
       [1.25549768e-311, 1.25549838e-311, 1.25549768e-311,
        1.25549769e-311, 1.25549768e-311, 1.25549768e-311,
        1.25549768e-311, 1.25549769e-311, 1.25549769e-311,
        1.25549838e-311],
       [1.25549768e-311, 1.25549768e-311, 1.25549768e-311,
        1.25549838e-311, 1.25549769e-311, 1.25549768e-311,
        1.25549769e-311, 1.25549768e-311, 1.25549768e-311,
        1.25549769e-311],
       [1.25549769e-311, 1.25549768e-311, 1.25549768e-311,
        1.25549769e-311, 1.25549768e-311, 1.25549768e-311,
        1.25549768e-311, 1.25549769e-311, 1.25549769e-311,
        1.2

#### arange
파이썬의 내장함수, `range()`함수와 동일한 기능을 하는 numpy배열 생성함수

In [ ]:
arage_array = np.arange(10,50)
arage_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 전치연산
배열의 행과 열의 위치를 전치시키는 방법 배열의 `T`속성으로 반환 받을 수 있음

In [ ]:
numpy_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
numpy_matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [19]:
numpy_3d.T

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

### 배열의 크기 변경
numpy 배열에서 원소의 개수를 유지한 상태로 배열의 형태를 변경하려 한다면 `reshape`메서드를 사용하여  
변경할 수 있음

In [21]:
numpy_array = np.zeros(12)
numpy_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
reshape_array = numpy_array.reshape(4, 3)
reshape_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
reshape_array = numpy_array.reshape(2, 6)
reshape_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

numpy 배열의 원소는 개수가 정해져 있기 때문에 `reshape`메서드에 하나의 인자로 -1을 넣게 되면 다른 인자들을 통해서 추론하여 지정

In [28]:
reshape_array = numpy_array.reshape(3, -1)
reshape_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
reshape_array = numpy_array.reshape(5 ,-1)

ValueError: cannot reshape array of size 12 into shape (5,newaxis)

만약 `reshape`메서드 인자들을 곱한 결과가 기존 배열의 원소의 총 합과 다르면 에러가 발생  
-1로 지정한 인자가 있을 때 해당 인자의 곱으로 총합을 계산할 수 없는 경우 에러가 발생

다차원 배열을 무조건 1차원 배열로 변경하려 한다면 `flatten`이나 `ravel`메서드를 사용

In [34]:
numpy_matrix = np.empty((3, 4))
numpy_matrix

array([[1.11743093e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.06099790e-312, 2.00416888e-052, 9.32260341e+164,
        3.69847213e-057],
       [1.80194815e+185, 7.79499468e-071, 1.09340090e-042,
        2.31814203e-056]])

In [36]:
numpy_array = numpy_matrix.flatten()
numpy_array

array([1.11743093e-311, 3.16202013e-322, 0.00000000e+000, 0.00000000e+000,
       1.06099790e-312, 2.00416888e-052, 9.32260341e+164, 3.69847213e-057,
       1.80194815e+185, 7.79499468e-071, 1.09340090e-042, 2.31814203e-056])

In [37]:
numpy_array = numpy_matrix.ravel()
numpy_array

array([1.11743093e-311, 3.16202013e-322, 0.00000000e+000, 0.00000000e+000,
       1.06099790e-312, 2.00416888e-052, 9.32260341e+164, 3.69847213e-057,
       1.80194815e+185, 7.79499468e-071, 1.09340090e-042, 2.31814203e-056])

배열 사용에서 주의할 점은 *길이가 6인 1차원배열* 과 *5x1인 2차원 배열* , *1x5인 2차원 배열* 은 서로 각각 다른 배열  
(요소의 개수와 내용, 순서가 모두 같더라도 형태가 다르면 다를 배열) 

차원을 한 차원 증가시키고자 한다면 `numpy.newaxis`속성으로 차원을 증가 시킬 수 있음

In [39]:
numpy_array

array([1.11743093e-311, 3.16202013e-322, 0.00000000e+000, 0.00000000e+000,
       1.06099790e-312, 2.00416888e-052, 9.32260341e+164, 3.69847213e-057,
       1.80194815e+185, 7.79499468e-071, 1.09340090e-042, 2.31814203e-056])

In [40]:
newaxis_array = numpy_array[:, np.newaxis]
newaxis_array

array([[1.11743093e-311],
       [3.16202013e-322],
       [0.00000000e+000],
       [0.00000000e+000],
       [1.06099790e-312],
       [2.00416888e-052],
       [9.32260341e+164],
       [3.69847213e-057],
       [1.80194815e+185],
       [7.79499468e-071],
       [1.09340090e-042],
       [2.31814203e-056]])

### 배열 연결하기
행의 수나 열의 수가 같은 두 개 이상의 배열을 연결하는 방법  
- `hstack` : 행의 수가 같은 두 개 이상의 배열을 연결  
- `vstack` : 열의 수가 같은 두 개 이상의 배열을 연결
- `dstack` : 행과 열의 수가 같은 두 개 이상의 배열을 연결

In [43]:
zeros_array = np.zeros((3, 4))
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
ones_array = np.ones((3, 2))
one


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [48]:
hstack_array = np.hstack([zeros_array, ones_array])
hstack_array


array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

In [54]:
zeros_array = np.zeros((3, 4))
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
ones_array = np.ones((2, 4))
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [58]:
vstack_array = np.vstack([zeros_array, ones_array])
vstack_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
zeros_array = np.zeros((3, 3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
ones_array = np.ones((3, 3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [62]:
dstack_array = np.dstack([zeros_array, ones_array])
dstack_array

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])